### ISSUE TITLE
Could we get energy symbol?

### ISSUE THREAD

**Issue by taw** [micku/mana-cost#2]
It's not technically mana symbol, but fairly similar.

**Comment by micku** [comment]
Seems legit, I'm out of magic for some time now, never seen it :)  
I'll work on it as soon as I can, I'll accept pull requests too ;)

**Comment by taw** [comment]
[There's some in this thread](http://www.slightlymagic.net/forum/viewtopic.php?f=15&t=4430&sid=a856194efe30239e4f6d904e539105a9&start=45). I'm not even sure how to concatenate svgs.

**Comment by micku** [comment]
No problem @taw, I'll check it out in some days.  
Thank you for pointing it out.
